-- ============================================================
--  SPIN & WIN  —  demo / seed data
--  Run AFTER schema.sql on a fresh database.
--  Fixed UUIDs are used so foreign keys line up cleanly.
--
--  NOTE on logins: password_hash values below are PLACEHOLDERS.
--  Real hashes are generated by the backend (Phase 2) create-user
--  script. Until then these users exist for FK/demo purposes only.
-- ============================================================

BEGIN;

-- ---------- store ----------
INSERT INTO stores (id, code, name, city, phone) VALUES
('11111111-1111-1111-1111-111111111111', 'MAIN', 'Ashoka Enterprises — Main Store', 'Patiala', '9999999999');

-- ---------- users ----------
INSERT INTO users (id, username, email, password_hash, full_name, role, store_id) VALUES
('22222222-2222-2222-2222-222222222201', 'superadmin', 'super@ashoka.test', 'PLACEHOLDER_SET_IN_PHASE2', 'Super Admin', 'SUPER_ADMIN', NULL),
('22222222-2222-2222-2222-222222222202', 'mainadmin',  'admin@ashoka.test', 'PLACEHOLDER_SET_IN_PHASE2', 'Main Store Admin', 'STORE_ADMIN', '11111111-1111-1111-1111-111111111111'),
('22222222-2222-2222-2222-222222222203', 'staff1',     'staff1@ashoka.test','PLACEHOLDER_SET_IN_PHASE2', 'Counter Staff 1', 'STAFF', '11111111-1111-1111-1111-111111111111');

-- ---------- employee (linked to staff login) ----------
INSERT INTO employees (id, store_id, user_id, code, name, phone) VALUES
('33333333-3333-3333-3333-333333333301', '11111111-1111-1111-1111-111111111111', '22222222-2222-2222-2222-222222222203', 'EMP01', 'Counter Staff 1', '8888888888');

-- ---------- products ----------
INSERT INTO products (id, sku, brand, model, name, category, default_price) VALUES
('44444444-4444-4444-4444-444444444401', 'SAM-A14',  'Samsung', 'Galaxy A14', 'Samsung Galaxy A14', 'MOBILE', 14999.00),
('44444444-4444-4444-4444-444444444402', 'VIVO-V30', 'Vivo',    'V30',        'Vivo V30',           'MOBILE', 29999.00),
('44444444-4444-4444-4444-444444444403', 'APL-15',   'Apple',   'iPhone 15',  'Apple iPhone 15',    'MOBILE', 69999.00);

-- ---------- price slabs (global) ----------
INSERT INTO price_slabs (id, store_id, name, min_price, max_price, priority) VALUES
('55555555-5555-5555-5555-555555555501', NULL, 'Slab 10k–19,999', 10000.00, 19999.99, 10),
('55555555-5555-5555-5555-555555555502', NULL, 'Slab 20k–29,999', 20000.00, 29999.99, 20),
('55555555-5555-5555-5555-555555555503', NULL, 'Slab 30k+',        30000.00, NULL,     30);

-- ---------- prizes ----------
INSERT INTO prizes (id, name, value, category, priority) VALUES
('66666666-6666-6666-6666-666666666601', '₹100 Voucher',    100.00,  'VOUCHER',   1),
('66666666-6666-6666-6666-666666666602', '₹500 Voucher',    500.00,  'VOUCHER',   2),
('66666666-6666-6666-6666-666666666603', 'Mobile Cover',    199.00,  'ACCESSORY', 3),
('66666666-6666-6666-6666-666666666604', 'Earphones',       499.00,  'ACCESSORY', 4),
('66666666-6666-6666-6666-666666666605', 'Smartwatch',      1999.00, 'ACCESSORY', 5),
('66666666-6666-6666-6666-666666666606', 'Premium Earbuds', 2999.00, 'ACCESSORY', 6),
('66666666-6666-6666-6666-666666666607', '₹2,000 Voucher',  2000.00, 'VOUCHER',   7);

-- ---------- inventory (global pool: store_id NULL) ----------
INSERT INTO prize_inventory (id, prize_id, store_id, quantity_initial, quantity_remaining, low_stock_threshold) VALUES
('77777777-7777-7777-7777-777777777701', '66666666-6666-6666-6666-666666666601', NULL, 500, 500, 50),
('77777777-7777-7777-7777-777777777702', '66666666-6666-6666-6666-666666666602', NULL, 300, 300, 30),
('77777777-7777-7777-7777-777777777703', '66666666-6666-6666-6666-666666666603', NULL, 100, 100, 10),
('77777777-7777-7777-7777-777777777704', '66666666-6666-6666-6666-666666666604', NULL,  50,  50, 10),
('77777777-7777-7777-7777-777777777705', '66666666-6666-6666-6666-666666666605', NULL,  20,  19,  5),  -- 1 already won below
('77777777-7777-7777-7777-777777777706', '66666666-6666-6666-6666-666666666606', NULL,  15,  15,  5),
('77777777-7777-7777-7777-777777777707', '66666666-6666-6666-6666-666666666607', NULL,  50,  50,  5);

-- ---------- prize rules (slab -> prize + weight) ----------
-- Slab 10k–19,999
INSERT INTO prize_rules (slab_id, prize_id, weight) VALUES
('55555555-5555-5555-5555-555555555501', '66666666-6666-6666-6666-666666666601', 50),  -- ₹100
('55555555-5555-5555-5555-555555555501', '66666666-6666-6666-6666-666666666603', 30),  -- Cover
('55555555-5555-5555-5555-555555555501', '66666666-6666-6666-6666-666666666604', 20);  -- Earphones
-- Slab 20k–29,999  (matches the weights example in your spec, section 7)
INSERT INTO prize_rules (slab_id, prize_id, weight) VALUES
('55555555-5555-5555-5555-555555555502', '66666666-6666-6666-6666-666666666601', 50),  -- ₹100
('55555555-5555-5555-5555-555555555502', '66666666-6666-6666-6666-666666666602', 25),  -- ₹500
('55555555-5555-5555-5555-555555555502', '66666666-6666-6666-6666-666666666604', 15),  -- Earphones
('55555555-5555-5555-5555-555555555502', '66666666-6666-6666-6666-666666666605',  8),  -- Smartwatch
('55555555-5555-5555-5555-555555555502', '66666666-6666-6666-6666-666666666607',  2);  -- ₹2000
-- Slab 30k+
INSERT INTO prize_rules (slab_id, prize_id, weight) VALUES
('55555555-5555-5555-5555-555555555503', '66666666-6666-6666-6666-666666666602', 40),  -- ₹500
('55555555-5555-5555-5555-555555555503', '66666666-6666-6666-6666-666666666604', 25),  -- Earphones
('55555555-5555-5555-5555-555555555503', '66666666-6666-6666-6666-666666666605', 20),  -- Smartwatch
('55555555-5555-5555-5555-555555555503', '66666666-6666-6666-6666-666666666606', 10),  -- Premium Earbuds
('55555555-5555-5555-5555-555555555503', '66666666-6666-6666-6666-666666666607',  5);  -- ₹2000

-- ---------- TV device ----------
INSERT INTO tv_devices (id, store_id, code, name, pairing_code) VALUES
('e0e0e0e0-e0e0-e0e0-e0e0-e0e0e0e0e001', '11111111-1111-1111-1111-111111111111', 'TV-001', 'Main Store TV', 'PAIR-MAIN-01');

-- ---------- customers ----------
INSERT INTO customers (id, mobile, name) VALUES
('99999999-9999-9999-9999-999999999901', '9812300001', 'Demo Customer A'),
('99999999-9999-9999-9999-999999999902', '9812300002', 'Demo Customer B');

-- ---------- bills + items ----------
-- Bill 1: iPhone (slab 30k+), ALREADY PLAYED -> won Smartwatch
INSERT INTO bills (id, store_id, bill_number, bill_date, customer_id, employee_id, total_amount, spins_allowed, spins_used, spin_status) VALUES
('aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaa01', '11111111-1111-1111-1111-111111111111', 'INV-1001', current_date, '99999999-9999-9999-9999-999999999901', '33333333-3333-3333-3333-333333333301', 69999.00, 1, 1, 'PLAYED');
INSERT INTO bill_items (id, bill_id, product_id, brand, model, serial_imei, selling_price, is_spin_item) VALUES
('bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbb01', 'aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaa01', '44444444-4444-4444-4444-444444444403', 'Apple', 'iPhone 15', '350000000000001', 69999.00, true);

-- Bill 2: Vivo V30 (slab 20k–29,999), NOT yet played
INSERT INTO bills (id, store_id, bill_number, bill_date, customer_id, employee_id, total_amount, spins_allowed, spins_used, spin_status) VALUES
('aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaa02', '11111111-1111-1111-1111-111111111111', 'INV-1002', current_date, '99999999-9999-9999-9999-999999999902', '33333333-3333-3333-3333-333333333301', 29999.00, 1, 0, 'NOT_PLAYED');
INSERT INTO bill_items (id, bill_id, product_id, brand, model, serial_imei, selling_price, is_spin_item) VALUES
('bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbb02', 'aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaa02', '44444444-4444-4444-4444-444444444402', 'Vivo', 'V30', '350000000000002', 29999.00, true);

-- ---------- one completed spin (Bill 1 won Smartwatch) ----------
INSERT INTO spin_sessions (id, store_id, tv_device_id, bill_id, bill_item_id, customer_id, price_slab_id, qualifying_price, pairing_code, status, connected_at, spun_at, completed_at) VALUES
('cccccccc-cccc-cccc-cccc-cccccccccc01', '11111111-1111-1111-1111-111111111111', 'e0e0e0e0-e0e0-e0e0-e0e0-e0e0e0e0e001', 'aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaa01', 'bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbb01', '99999999-9999-9999-9999-999999999901', '55555555-5555-5555-5555-555555555503', 69999.00, 'USED-DEMO-0001', 'COMPLETED', now() - interval '10 min', now() - interval '9 min', now() - interval '9 min');

-- inventory ledger: initial + the deduct for the smartwatch win
INSERT INTO inventory_ledger (id, inventory_id, txn_type, quantity_delta, balance_after, note) VALUES
('f0f0f0f0-f0f0-f0f0-f0f0-f0f0f0f0f001', '77777777-7777-7777-7777-777777777705', 'INITIAL', 20, 20, 'Opening stock'),
('f0f0f0f0-f0f0-f0f0-f0f0-f0f0f0f0f002', '77777777-7777-7777-7777-777777777705', 'DEDUCT',  -1, 19, 'Won on INV-1001');

INSERT INTO spin_results (id, session_id, prize_id, prize_name, prize_value, slab_id, is_forced, inventory_ledger_id) VALUES
('dddddddd-dddd-dddd-dddd-dddddddddd01', 'cccccccc-cccc-cccc-cccc-cccccccccc01', '66666666-6666-6666-6666-666666666605', 'Smartwatch', 1999.00, '55555555-5555-5555-5555-555555555503', false, 'f0f0f0f0-f0f0-f0f0-f0f0-f0f0f0f0f002');

-- ---------- global settings ----------
INSERT INTO app_settings (store_id, key, value) VALUES
(NULL, 'branding', '{"company_name":"Ashoka Enterprises","game_title":"SPIN & WIN","currency":"INR","logo_url":null}'::jsonb),
(NULL, 'game',     '{"default_spins_per_bill":1,"animation_seconds":6,"confetti":true,"sound":true}'::jsonb);

COMMIT;
